title: Math Club Site
description: All our activities and projects
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


domain: dheeraj-murthy.github.io
url: https://dheeraj-murthy.github.io
baseurl: /website-mathclub 

collections:
  posts:
    output: true
    permalink: /activities/:path/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
minima:
  show_rss_footer_link: false

markdown: kramdown
kramdown:
  input: GFM  # GitHub-Flavored Markdown
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  syntax_highlighter: rouge
